### ISSUE TITLE
trouble running sup3rwind example

### ISSUE THREAD

**Issue by dschneider-wxs** [NREL/sup3r#322]
Hi - 
I am interested in sup3rwind for downscaling wind but am having trouble with the wind example. The env.yml in the wind example folder isn't recognized by conda and I noticed has several local dependencies. I burned some tokens to find an environment that could at least run the imports and preprocessing, although I had to add some imports in a module to be able to depickle the 202401 models (I guess the current code isn't compatible with the v1 models). I downloaded era5 and gtopo30 and then ran strategy and forward pass but hit an error (see below).

I also tried switching to the 0.1.4 tag but there is no example notebook in that ref. I tried following the sup3r-pipeline workflow outlined in README.rst by updating the configs but i couldn't figure out how to run the cli. 
`supr3` command wasn't found and `pixi run  sup3r-pipeline from-config -c config_pipeline.json`
I created a 0.1.4 env with `pixi install` from the root.

do you have any suggestions getting this to work?

```
DEBUG - 2026-09-01 01:21:32,229 [utilities.py:126] : Initialized ForwardPass with:
{ 'node_index': 0,
  'strategy': ForwardPassStrategy(file_paths=[ './tmp/2021_01_2m_dewpoint_temperature.nc',
                                               './tmp/2021_01_2m_temperature.nc',
                                               './tmp/2021_01_convective_available_potential_energy.nc',
                                               './tmp/2021_01_friction_velocity.nc',
                                               './tmp/2021_01_instantaneous_moisture_flux.nc',
                                               './tmp/2021_01_k_index.nc',
                                               './tmp/2021_01_orog.nc',
                                               './tmp/2021_01_surface_latent_heat_flux.nc',
                                               './tmp/2021_01_surface_pressure.nc',
                                               './tmp/2021_01_u.nc',
                                               './tmp/2021_01_v.nc',
                                               './tmp/2021_01_zg.nc'],
                                  model_kwargs={ 'model_dirs': [ 'models/sup3rwind_models_202401/sup3rwind_wind_step1_3x_1x_14f',
                                                                 'models/sup3rwind_models_202401/sup3rwind_wind_step2_5x_1x_14f',
                                                                 'models/sup3rwind_models_202401/sup3rwind_wind_step3_1x_12x_14f']},
                                  fwp_chunk_shape=(30, 30, 40),
                                  spatial_pad=5,
                                  temporal_pad=5,
                                  min_width=(4, 4, 4),
                                  model_class='MultiStepGan',
                                  out_pattern='./output/ukraine_chunk_{file_id}.nc',
                                  input_handler_name='DataHandler',
                                  input_handler_kwargs={ 'cache_kwargs': { 'cache_pattern': './cache/{feature}.nc'},
                                                         'chunks': { 'south_north': 30,
                                                                     'time': 100,
                                                                     'west_east': 30},
                                                         'features': [ 'pressure_0m',
                                                                       'temperature_2m',
                                                                       'ie',
                                                                       'zust',
                                                                       'slhf',
                                                                       'd2m',
                                                                       'cape',
                                                                       'kx',
                                                                       'U_10m',
                                                                       'V_10m',
                                                                       'U_100m',
                                                                       'V_100m',
                                                                       'U_200m',
                                                                       'V_200m'],
                                                         'file_paths': [ './tmp/2021_01_2m_dewpoint_temperature.nc',
                                                                         './tmp/2021_01_2m_temperature.nc',
                                                                         './tmp/2021_01_convective_available_potential_energy.nc',
                                                                         './tmp/2021_01_friction_velocity.nc',
                                                                         './tmp/2021_01_instantaneous_moisture_flux.nc',
                                                                         './tmp/2021_01_k_index.nc',
                                                                         './tmp/2021_01_orog.nc',
                                                                         './tmp/2021_01_surface_latent_heat_flux.nc',
                                                                         './tmp/2021_01_surface_pressure.nc',
                                                                         './tmp/2021_01_u.nc',
                                                                         './tmp/2021_01_v.nc',
                                                                         './tmp/2021_01_zg.nc'],
                                                         'shape': [30, 30],
                                                         'target': [43.0, 22.0],
                                                         'time_slice': slice(0, 100, None)},
                                  exo_handler_kwargs={ 'topography': { 'chunks': { 'south_north': 30,
                                                                                   'west_east': 30},
                                                                       'file_paths': './tmp/*.nc',
                                                                       'source_files': './datasets/ukraine_topo.nc'}},
                                  bias_correct_method=None,
                                  bias_correct_kwargs={},
                                  allowed_const=None,
                                  incremental=True,
                                  output_workers=1,
                                  invert_uv=True,
                                  nn_fill=True,
                                  pass_workers=1,
                                  max_nodes=1,
                                  head_node=False,
                                  redistribute_chunks=False,
                                  use_cpu=True)}
DEBUG - 2026-09-01 01:21:32,232 [utilities.py:131] : Memory usage is 18.290 GB out of 404.313 GB
DEBUG - 2026-09-01 01:21:32,283 [strategy.py:608] : Initializing ForwardPassChunk with: { 'chunk': 0,
  'fwp_chunk_shape': (30, 30, 40),
  'lr_pad_slice': (slice(0, 29, 1), slice(0, 29, 1)),
  'n_node_chunks': 1,
  'spatial_chunk': 0,
  'spatial_pad': 5,
  'temporal_chunk': 0,
  'temporal_pad': 5,
  'ti_pad_slice': slice(0, 24, 1)}
DEBUG - 2026-09-01 01:21:32,284 [strategy.py:613] : Getting input data for chunk_index=0.
DEBUG - 2026-09-01 01:21:32,285 [exo.py:255] : Getting exo data chunk for lr_slices=[slice(0, 29, 1), slice(0, 29, 1), slice(0, 24, 1)].
DEBUG - 2026-09-01 01:21:32,287 [utilities.py:331] : Call to get_chunk finished in 0.00127 seconds
WARNING - 2026-09-01 01:21:32,288 [utilities.py:578] : Received some upper case features: ['pressure_0m', 'temperature_2m', 'ie', 'zust', 'slhf', 'd2m', 'cape', 'kx', 'U_10m', 'V_10m', 'U_100m', 'V_100m', 'U_200m', 'V_200m']. Using ['pressure_0m', 'temperature_2m', 'ie', 'zust', 'slhf', 'd2m', 'cape', 'kx', 'u_10m', 'v_10m', 'u_100m', 'v_100m', 'u_200m', 'v_200m'] instead.
DEBUG - 2026-09-01 01:21:32,292 [strategy.py:549] : Loading data for chunk_index=0 into memory.
DEBUG - 2026-09-01 01:21:32,347 [utilities.py:331] : Call to prep_chunk_data finished in 0.06131 seconds
DEBUG - 2026-09-01 01:21:32,353 [base.py:534] : Getting high resolution time indices
DEBUG - 2026-09-01 01:21:32,354 [base.py:535] : Low res times: 2021-01-01 00:00:00 to 2021-01-01 18:00:00
DEBUG - 2026-09-01 01:21:32,364 [base.py:553] : High res times: 2021-01-01 00:00:00 to 2021-01-01 18:55:00
DEBUG - 2026-09-01 01:21:32,371 [forward_pass.py:148] : Padded input data shape from (29, 29, 24, 14) to (39, 39, 29, 14) using mode "reflect" with padding argument: ((5, 5), (5, 5), (5, 0))
DEBUG - 2026-09-01 01:21:32,463 [forward_pass.py:180] : Got exo data for feature: topography, model step: 0, s_enhance: 1, t_enhance: 1
DEBUG - 2026-09-01 01:21:32,533 [forward_pass.py:180] : Got exo data for feature: topography, model step: 1, s_enhance: 3, t_enhance: 1
DEBUG - 2026-09-01 01:21:32,604 [forward_pass.py:180] : Got exo data for feature: topography, model step: 2, s_enhance: 3, t_enhance: 1
DEBUG - 2026-09-01 01:21:32,727 [forward_pass.py:180] : Got exo data for feature: topography, model step: 3, s_enhance: 15, t_enhance: 1
DEBUG - 2026-09-01 01:21:32,730 [forward_pass.py:678] : Running forward pass for chunk_index=0.
INFO - 2026-09-01 01:21:32,738 [base.py:210] : Loading GAN from disk in directory: models/sup3rwind_models_202401/sup3rwind_wind_step1_3x_1x_14f
DEBUG - 2026-09-01 01:21:32,739 [base.py:211] : Active python environment versions: 
{   'cftime': '1.6.5',
    'dask': '2026.1.2',
    'h5netcdf': '1.8.1',
    'netCDF4': '1.6.5',
    'nrel-phygnn': '0.0.30',
    'nrel-rex': '0.2.98',
    'numpy': '1.24.3',
    'pandas': '2.3.3',
    'python': '3.11.16 | packaged by conda-forge | (main, Aug 21 2026, '
              '22:44:51) [GCC 14.4.0]',
    'sklearn': '1.9.0',
    'sup3r': '0.2.9.dev50+g2ecda930a.d20260901',
    'tensorflow': '2.12.1',
    'xarray': '2025.6.1'}
DEBUG - 2026-09-01 01:21:32,747 [abstract.py:535] : Loading model from disk that was created with the following package versions: 
{ 'dask': '2023.11.0',
  'netCDF4': '1.5.8',
  'nrel-phygnn': '0.0.25',
  'nrel-rex': '0.2.84',
  'numpy': '1.26.2',
  'pandas': '2.1.3',
  'python': '3.9.18 (main, Sep 11 2023, 13:41:44) \n[GCC 11.2.0]',
  'sklearn': '1.3.2',
  'sup3r': '0.1.2',
  'tensorflow': '2.8.0',
  'xarray': '2023.10.1'}
INFO - 2026-09-01 01:21:32,982 [base.py:210] : Loading GAN from disk in directory: models/sup3rwind_models_202401/sup3rwind_wind_step2_5x_1x_14f
DEBUG - 2026-09-01 01:21:32,984 [base.py:211] : Active python environment versions: 
{   'cftime': '1.6.5',
    'dask': '2026.1.2',
    'h5netcdf': '1.8.1',
    'netCDF4': '1.6.5',
    'nrel-phygnn': '0.0.30',
    'nrel-rex': '0.2.98',
    'numpy': '1.24.3',
    'pandas': '2.3.3',
    'python': '3.11.16 | packaged by conda-forge | (main, Aug 21 2026, '
              '22:44:51) [GCC 14.4.0]',
    'sklearn': '1.9.0',
    'sup3r': '0.2.9.dev50+g2ecda930a.d20260901',
    'tensorflow': '2.12.1',
    'xarray': '2025.6.1'}
DEBUG - 2026-09-01 01:21:32,991 [abstract.py:535] : Loading model from disk that was created with the following package versions: 
{ 'dask': '2023.3.2',
  'netCDF4': '1.5.8',
  'nrel-phygnn': '0.0.23',
  'nrel-reV': '0.7.3',
  'nrel-rex': '0.2.80',
  'numpy': '1.23.5',
  'pandas': '2.0.0',
  'python': '3.9.16 (main, Mar  8 2023, 14:00:05) \n[GCC 11.2.0]',
  'sklearn': '1.2.2',
  'sup3r': '0.1.0',
  'tensorflow': '2.4.1',
  'xarray': '2023.2.0'}
INFO - 2026-09-01 01:21:33,328 [base.py:210] : Loading GAN from disk in directory: models/sup3rwind_models_202401/sup3rwind_wind_step3_1x_12x_14f
DEBUG - 2026-09-01 01:21:33,329 [base.py:211] : Active python environment versions: 
{   'cftime': '1.6.5',
    'dask': '2026.1.2',
    'h5netcdf': '1.8.1',
    'netCDF4': '1.6.5',
    'nrel-phygnn': '0.0.30',
    'nrel-rex': '0.2.98',
    'numpy': '1.24.3',
    'pandas': '2.3.3',
    'python': '3.11.16 | packaged by conda-forge | (main, Aug 21 2026, '
              '22:44:51) [GCC 14.4.0]',
    'sklearn': '1.9.0',
    'sup3r': '0.2.9.dev50+g2ecda930a.d20260901',
    'tensorflow': '2.12.1',
    'xarray': '2025.6.1'}
DEBUG - 2026-09-01 01:21:33,334 [abstract.py:535] : Loading model from disk that was created with the following package versions: 
{ 'dask': '2023.11.0',
  'netCDF4': '1.5.8',
  'nrel-phygnn': '0.0.25',
  'nrel-rex': '0.2.84',
  'numpy': '1.26.2',
  'pandas': '2.1.3',
  'python': '3.9.18 (main, Sep 11 2023, 13:41:44) \n[GCC 11.2.0]',
  'sklearn': '1.3.2',
  'sup3r': '0.1.1',
  'tensorflow': '2.8.0',
  'xarray': '2023.10.1'}
DEBUG - 2026-09-01 01:21:35,248 [multi_step.py:245] : Data input to model #1 of 3 has shape (1, 39, 39, 29, 14)
ERROR - 2026-09-01 01:21:35,269 [multi_step.py:273] : Could not run model #1 of 3 "<sup3r.models.base.Sup3rGan object at 0x75fbd4232410>" on tensor of shape (1, 39, 39, 29, 14)
Traceback (most recent call last):
  File "/home/dominik/Repos/sup3r/sup3r/models/multi_step.py", line 254, in generate
    hi_res = model.generate(
             ^^^^^^^^^^^^^^^
  File "/home/dominik/Repos/sup3r/sup3r/models/abstract.py", line 1375, in generate
    hi_res = self.generator.layers[0](low_res, training=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dominik/Repos/sup3r/.pixi/envs/default/lib/python3.11/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/dominik/Repos/sup3r/.pixi/envs/default/lib/python3.11/site-packages/keras/engine/base_layer.py", line 1047, in __call__
    inputs, args, kwargs = self._call_spec.split_out_first_arg(args, kwargs)
                           ^^^^^^^^^^^^^^^
AttributeError: 'FlexiblePadding' object has no attribute '_call_spec'
ERROR - 2026-09-01 01:21:35,271 [forward_pass.py:243] : Forward pass failed on chunk with shape (1, 39, 39, 29, 14).
Traceback (most recent call last):
  File "/home/dominik/Repos/sup3r/sup3r/models/multi_step.py", line 254, in generate
    hi_res = model.generate(
             ^^^^^^^^^^^^^^^
  File "/home/dominik/Repos/sup3r/sup3r/models/abstract.py", line 1375, in generate
    hi_res = self.generator.layers[0](low_res, training=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dominik/Repos/sup3r/.pixi/envs/default/lib/python3.11/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/dominik/Repos/sup3r/.pixi/envs/default/lib/python3.11/site-packages/keras/engine/base_layer.py", line 1047, in __call__
    inputs, args, kwargs = self._call_spec.split_out_first_arg(args, kwargs)
                           ^^^^^^^^^^^^^^^
AttributeError: 'FlexiblePadding' object has no attribute '_call_spec'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dominik/Repos/sup3r/sup3r/pipeline/forward_pass.py", line 238, in run_generator
    hi_res = fun(data_chunk, exogenous_data=exo_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dominik/Repos/sup3r/sup3r/utilities/utilities.py", line 322, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dominik/Repos/sup3r/sup3r/models/multi_step.py", line 274, in generate
    raise RuntimeError(msg) from e
RuntimeError: Could not run model #1 of 3 "<sup3r.models.base.Sup3rGan object at 0x75fbd4232410>" on tensor of shape (1, 39, 39, 29, 14)
```

**Comment by bnb32** [comment]
Hi @dschneider-wxs. Sorry for the broken environment. I have pushed a new env.yml. I am able to run the notebook successfully after creating a fresh conda env from this file. The 202401 models were created with an ancient tensorflow version but the 202407 models should work fine with sup3r 0.2.4 (the version in the env.yml). Let me know how this goes.

**Comment by dschneider-wxs** [comment]
@bnb32 Thanks for the update. When running the ForwardPassStrategy I get this error
`OSError: Could not find valid coordinates in given files: ['./datasets/exogenous_data/gt30e020n90.nc']`
I downloaded the geotif for ukraine and converted it to .nc with rioxarray.  Is there a specific format for the coordinates?

```
# /// script
# dependencies = [
#   "rioxarray",
#   "xarray[io]",
# ]
# ///




import rioxarray
from pathlib import Path
import sys

input = sys.argv[1]


data = rioxarray.open_rasterio(input)

data=data.squeeze("band", drop=True)
data = data.rename('topography')
data.attrs['units']='m'

output = Path(input).with_suffix('.nc')

data.to_netcdf(output)
```

**Comment by bnb32** [comment]
@dschneider-wxs Yeah the file should have latitude and longitude.

**Comment by dschneider-wxs** [comment]
Perfect, the notebook ran (I commented out the bias correction portion). Thanks!
for future reference, added to the conversion script:
```
data = data.rename(
    {
        "x": "longitude",
        "y": "latitude",
    }
)
```
